# Traefik entryPoints configuration for HTTP and HTTPS.
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
persistence:
  enabled: true
  size: 128Mi

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
    port: 80
  websecure:
    port: 443
certificatesResolvers:
  duckdns:
    acme:
      # email: "{{ letsencrypt_email }}"
      storage: /data/acme.json
      dnsChallenge:
        provider: duckdns
        delayBeforeCheck: 60
        disablePropagationCheck: true

env:
  - name: TRAEFIK_CERTIFICATESRESOLVERS_DUCKDNS_ACME_EMAIL
    valueFrom:
      secretKeyRef:
        name: duckdns-secret
        key: duckdns_email
  - name: DUCKDNS_TOKEN
    valueFrom:
      secretKeyRef:
        name: duckdns-secret
        key: duckdns_token
  - name: DUCKDNS_PROPAGATION_TIMEOUT
    value: "60"

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command: ["sh", "-c", "ls -la /; touch /data/acme.json; chmod -v 600 /data/acme.json"]
      volumeMounts:
      - mountPath: /data
        name: data
providers:
  kubernetesCRD:
    enabled: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
