---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula
  namespace: homelab
  labels:
    app: nebula
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nebula
  template:
    metadata:
      namespace: homelab
      labels:
        app: nebula
    spec:
      containers:
        - name: nebula
          image: ghcr.io/lovelaze/nebula-sync:latest
          envFrom:
            - secretRef:
                name: pihole-nebula-sync
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "000"
            - name: TZ
              value: "Asia/Kolkata"
            - name: FULL_SYNC
              value: "true"
            - name: RUN_GRAVITY
              value: "true"
            - name: CRON
              value: "*/1 * * * *"
