---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula
  labels:
    app: nebula
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nebula
  template:
    metadata:
      labels:
        app: nebula
    spec:
      containers:
      - name: nebula-sync
        image: ghcr.io/lovelaze/nebula-sync:latest
        resources:
            limits:
              cpu: "4"
              memory: 4Gi
        envFrom:
          - secretRef:
              name: pihole-nebula-sync
        env:
          - name: FULL_SYNC
            value: "true"
          - name: RUN_GRAVITY
            value: "true"
          - name: CRON
            value: "*/5 * * * *"
---
apiVersion: v1
kind: Service
metadata:
  name: nebula
  labels:
    app: nebula
spec:
  selector:
    app: nebula
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP