---
# helm chart values
namespaceOverride: "argocd"
global:
  domain: argo.rrk.duckdns.org

# Redis storage
redis:
  persistence:
    enabled: true
    storageClass: "local-path-retain"  # Your MinIO CSI
    size: 10Gi

# Postgres storage
postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: "local-path-retain"
      size: 20Gi

# Ingress ONLY


# Metrics for your OTel/Prometheus
server:
  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - argo.rrk.duckdns.org
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s
# handle tls at ingress level and enable at argocd
configs:
  params:
    create: true
    server.insecure: true
