apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-stack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    targetRevision: "1.3.0"
    chart: alloy
    helm:
      releaseName: k8s-alloy-logs
      valueFiles:
        - $values/k8s-monitoring-values.yml
       # - $values/loki-values.yml
  - repoURL: https://github.com/wannabecoder11/k8s-homelab.git
    targetRevision: "HEAD"
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
