apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://imio.github.io/helm-charts
      chart: odoo
      targetRevision: "0.2.7"
      helm: 
        releaseName: odoo-install
        valueFiles:
          - $values/helm/odoo/odoo-values.yml
    - repoURL: https://github.com/wannabecoder11/k8s-homelab.git
      targetRevision: "HEAD"
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
