apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo
  namespace: argocd
spec:
  project: default
  source:

    chart: sealed-secrets
    targetRevision: 1.16.1
    helm:
      releaseName: sealed-secrets
    path: helm/odoo
    helm:
      valueFiles:
        - odoo-values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
