apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wannabecoder11/k8s-homelab.git
    targetRevision: HEAD
    path: helm/odoo
    helm:
      valueFiles:
        - odoo-values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
