apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-kube-stack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "79.12.0"
    chart: kube-prometheus-stack
    helm: 
      releaseName: prometheus-stack
      valueFiles:
        - $values/helm/prometheus-kube-stack-values.yml
  - repoURL: https://github.com/wannabecoder11/k8s-homelab.git
    targetRevision: HEAD
    path: helm
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
