apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
  - repoURL: https://github.com/traefik/traefik-helm-chart.git

    chart: traefik
    targetRevision: "main"
    helm:
      valueFiles:
        - helm/traefik/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
